### ISSUE TITLE
Docker based Quick Start is out of date

### ISSUE THREAD

**Issue by gcdev373** [gchq/stroom-docs#24]
Rather than using bounceIt.sh, is the recommended approach now to use the scripts in one of the tar archive release under https://github.com/gchq/stroom-resources/releases?

The quick start should at least explain when (and how) to use those scripts and when to use bounceIt.sh

**Comment by jc064522** [comment]
Like this? 
https://github.com/gchq/stroom-docs/commit/046d509b499fcb74cdf924831c82b6423b2770f8#diff-899fdbfdb822cd0e75ac207af430f906

**Comment by at055612** [comment]
This has now been updated
